import json


country = """
   US("United States of America","United States of America","US","USA",840,1),
   CA("Canada","Canada","CA","CAN",124,2),
   AF("Afghanistan","Afghanistan","AF","AFG",4,3),
   AL("Albania","Albania","AL","ALB",8,4),
   DZ("Algeria","Algeria","DZ","DZA",12,5),
   AR("Argentina","Argentina","AR","ARG",32,6),
   AU("Australia","Australia","AU","AUS",36,7),
   AT("Austria","Austria","AT","AUT",40,8),
   BE("Belgium","Belgium","BE","BEL",56,9),
   BR("Brazil","Brazil","BR","BRA",76,10),
   BG("Bulgaria","Bulgaria","BG","BGR",100,11),
   CL("Chile","Chile","CL","CHL",152,12),
   CN("China","China","CN","CHN",156,13),
   CO("Colombia","Colombia","CO","COL",170,14),
   CR("Costa Rica","Costa Rica","CR","CRI",188,15),
   HR("Croatia","Croatia","HR","HRV",191,16),
   CZ("Czech Republic","Czech Republic","CZ","CZE",203,17),
   DK("Denmark","Denmark","DK","DNK",208,18),
   EC("Ecuador","Ecuador","EC","ECU",218,19),
   EG("Egypt","Egypt","EG","EGY",818,20),
   SV("El Salvador","El Salvador","SV","0",222,21),
   FI("Finland","Finland","FI","FIN",246,22),
   FR("France","France","FR","FRA",250,23),
   DE("Germany","Germany","DE","DEU",276,24),
   GR("Greece","Greece","GR","GRC",300,25),
   HK("Hong Kong","Hong Kong","HK","HKG",344,26),
   HU("Hungary","Hungary","HU","HUN",348,27),
   IN("India","India","IN","IND",356,28),
   ID("Indonesia","Indonesia","ID","IDN",360,29),
   IE("Ireland","Ireland","IE","IRL",372,30),
   IL("Israel","Israel","IL","ISR",376,31),
   IT("Italy","Italy","IT","ITA",380,32),
   JP("Japan","Japan","JP","JPN",392,33),
   JO("Jordan","Jordan","JO","JOR",400,34),
   KR("Korea, South","Korea, South","KR","KOR",410,35),
   KP("Korea, North","Korea, North","KP","PRK",408,36),
   LB("Lebanon","Lebanon","LB","LBN",422,37),
   MY("Malaysia","Malaysia","MY","MYS",458,38),
   MX("Mexico","Mexico","MX","MEX",484,39),
   MA("Morocco","Morocco","MA","MAR",504,40),
   NL("Netherlands","Netherlands","NL","NLD",528,41),
   NZ("New Zealand","New Zealand","NZ","NZL",554,42),
   NO("Norway","Norway","NO","NOR",578,43),
   PK("Pakistan","Pakistan","PK","PAK",586,44),
   PE("Peru","Peru","PE","PER",604,45),
   PH("Philippines","Philippines","PH","PHL",608,46),
   PL("Poland","Poland","PL","POL",616,47),
   PT("Portugal","Portugal","PT","PRT",620,48),
   PR("Puerto Rico","Puerto Rico","PR","PRI",630,49),
   RO("Romania","Romania","RO","ROU",642,50),
   RU("Russia","Russia","RU","RUS",643,51),
   SA("Saudi Arabia","Saudi Arabia","SA","SAU",682,52),
   SG("Singapore","Singapore","SG","SGP",702,53),
   ZA("South Africa","South Africa","ZA","ZAF",710,54),
   ES("Spain","Spain","ES","ESP",724,55),
   SE("Sweden","Sweden","SE","SWE",752,56),
   CH("Switzerland","Switzerland","CH","CHE",756,57),
   TW("Taiwan","Taiwan","TW","TWN",158,58),
   TH("Thailand","Thailand","TH","THA",764,59),
   TR("Turkey","Turkey","TR","TUR",792,60),
   UM("U.S. Minor Outlying Islands","U.S. Minor Outlying Islands","UM","UMI",581,61),
   UA("Ukraine","Ukraine","UA","UKR",804,62),
   AE("United Arab Emirates","United Arab Emirates","AE","ARE",784,63),
   GB("United Kingdom","United Kingdom","GB","GBR",826,64),
   VE("Venezuela","Venezuela","VE","VEN",862,65),
   OT("Other","Other","OT","0",0,67),
   AD("Andorra","Andorra","AD","AND",20,68),
   BY("Belarus","Belarus","BY","BLR",112,69),
   BA("Bosnia and Herzegovina","Bosnia and Herzegovina","BA","BIH",70,70),
   CY("Cyprus","Cyprus","CY","CYP",196,71),
   EE("Estonia","Estonia","EE","EST",233,72),
   FO("Faroe Islands","Faroe Islands","FO","FRO",234,73),
   GI("Gibraltar","Gibraltar","GI","GIB",292,74),
   GL("Greenland","Greenland","GL","GRL",304,75),
   IS("Iceland","Iceland","IS","ISL",352,76),
   LV("Latvia","Latvia","LV","LVA",428,77),
   LI("Liechtenstein","Liechtenstein","LI","LIE",438,78),
   LT("Lithuania","Lithuania","LT","LTU",440,79),
   LU("Luxembourg","Luxembourg","LU","LUX",442,80),
   MK("Macedonia","Macedonia","MK","MKD",807,81),
   MT("Malta","Malta","MT","MLT",470,82),
   MD("Moldova","Moldova","MD","MDA",498,83),
   MC("Monaco","Monaco","MC","MCO",492,84),
   SM("San Marino","San Marino","SM","SMR",674,85),
   SK("Slovakia","Slovakia","SK","0",703,87),
   SI("Slovenia","Slovenia","SI","SVN",705,88),
   VA("Vatican City","Vatican City","VA","VAT",336,89),
   AO("Angola","Angola","AO","AGO",24,90),
   AG("Antigua and Barbuda","Antigua and Barbuda","AG","ATG",28,91),
   AM("Armenia","Armenia","AM","ARM",51,92),
   AW("Aruba","Aruba","AW","ABW",533,93),
   AZ("Azerbaijan","Azerbaijan","AZ","AZE",31,94),
   BS("Bahamas","Bahamas","BS","BHS",44,95),
   BH("Bahrain","Bahrain","BH","BHR",48,96),
   BD("Bangladesh","Bangladesh","BD","BGD",50,97),
   BB("Barbados","Barbados","BB","BRB",52,98),
   BZ("Belize","Belize","BZ","BLZ",84,99),
   BJ("Benin","Benin","BJ","BEN",204,100),
   BM("Bermuda","Bermuda","BM","BMU",60,101),
   BO("Bolivia","Bolivia","BO","BOL",68,102),
   BW("Botswana","Botswana","BW","BWA",72,103),
   BN("Brunei Darussalam","Brunei Darussalam","BN","BRN",96,104),
   BF("Burkina Faso","Burkina Faso","BF","BFA",854,105),
   BI("Burundi","Burundi","BI","BDI",108,106),
   KH("Cambodia","Cambodia","KH","KHM",116,107),
   CM("Cameroon","Cameroon","CM","CMR",120,108),
   CV("Cape Verde","Cape Verde","CV","CPV",132,109),
   KY("Cayman Islands","Cayman Islands","KY","CYM",136,110),
   TD("Chad","Chad","TD","TCD",148,111),
   CG("Congo","Congo","CG","COG",178,112),
   CI("Ivory Coast","Ivory Coast","CI","CIV",384,113),
   CU("Cuba","Cuba","CU","CUB",192,114),
   DJ("Djibouti","Djibouti","DJ","DJI",262,115),
   DM("Dominica","Dominica","DM","DMA",212,116),
   DO("Dominican Republic","Dominican Republic","DO","DOM",214,117),
   ET("Ethiopia","Ethiopia","ET","ETH",231,118),
   FK("Falkland Islands","Falkland Islands","FK","FLK",238,119),
   FJ("Fiji","Fiji","FJ","FJI",242,120),
   GF("French Guiana","French Guiana","GF","GUF",254,121),
   PF("French Polynesia","French Polynesia","PF","PYF",258,122),
   GA("Gabon","Gabon","GA","GAB",266,123),
   GM("Gambia","Gambia","GM","GMB",270,124),
   GH("Ghana","Ghana","GH","GHA",288,125),
   GD("Grenada","Grenada","GD","GRD",308,126),
   GP("Guadeloupe","Guadeloupe","GP","GLP",312,127),
   GT("Guatemala","Guatemala","GT","GTM",320,128),
   GN("Guinea","Guinea","GN","GIN",324,129),
   GY("Guyana","Guyana","GY","GUY",328,130),
   HT("Haiti","Haiti","HT","HTI",332,131),
   HN("Honduras","Honduras","HN","HND",340,133),
   IR("Iran","Iran","IR","IRN",364,134),
   IQ("Iraq","Iraq","IQ","IRQ",368,135),
   JM("Jamaica","Jamaica","JM","JAM",388,136),
   KZ("Kazakhstan","Kazakhstan","KZ","KAZ",398,137),
   KE("Kenya","Kenya","KE","KEN",404,138),
   KW("Kuwait","Kuwait","KW","KWT",414,139),
   KG("Kyrgyzstan","Kyrgyzstan","KG","KGZ",417,140),
   LA("Laos","Laos","LA","LAO",418,141),
   LS("Lesotho","Lesotho","LS","LSO",426,142),
   LY("Libya","Libya","LY","LBY",434,143),
   MO("Macao","Macao","MO","MAC",446,144),
   MG("Madagascar","Madagascar","MG","MDG",450,145),
   MW("Malawi","Malawi","MW","MWI",454,146),
   MV("Maldives","Maldives","MV","MDV",462,147),
   MQ("Martinique","Martinique","MQ","MTQ",474,148),
   MR("Mauritania","Mauritania","MR","MRT",478,149),
   MU("Mauritius","Mauritius","MU","MUS",480,150),
   YT("Mayotte","Mayotte","YT","MYT",175,151),
   MN("Mongolia","Mongolia","MN","MNG",496,152),
   MZ("Mozambique","Mozambique","MZ","MOZ",508,153),
   MM("Myanmar","Myanmar","MM","MMR",104,154),
   NA("Namibia","Namibia","NA","NAM",516,155),
   NP("Nepal","Nepal","NP","NPL",524,156),
   AN("Netherlands Antilles","Netherlands Antilles","AN","ANT",530,157),
   NC("New Caledonia","New Caledonia","NC","NCL",540,158),
   NI("Nicaragua","Nicaragua","NI","NIC",558,159),
   NE("Niger","Niger","NE","NER",562,160),
   NG("Nigeria","Nigeria","NG","NGA",566,161),
   OM("Oman","Oman","OM","OMN",512,162),
   PA("Panama","Panama","PA","PAN",591,163),
   PG("Papua New Guinea","Papua New Guinea","PG","PNG",598,164),
   PY("Paraguay","Paraguay","PY","PRY",600,165),
   QA("Qatar","Qatar","QA","QAT",634,166),
   RW("Rwanda","Rwanda","RW","RWA",646,167),
   SN("Senegal","Senegal","SN","SEN",686,170),
   SC("Seychelles","Seychelles","SC","SYC",690,171),
   SO("Somalia","Somalia","SO","SOM",706,173),
   LK("Sri Lanka","Sri Lanka","LK","LKA",144,174),
   KN("St. Kitts and Nevis","St. Kitts and Nevis","KN","KNA",659,175),
   LC("St. Lucia","St. Lucia","LC","LCA",662,176),
   VC("St. Vincent and the Grenadines","St. Vincent and the Grenadines","VC","VCT",670,177),
   SD("Sudan","Sudan","SD","SDN",736,178),
   SR("Suriname","Suriname","SR","SUR",740,179),
   XC("Tahiti","Tahiti","XC","0",0,180),
   TJ("Tajikistan","Tajikistan","TJ","TJK",762,181),
   TZ("Tanzania","Tanzania","TZ","TZA",834,182),
   TG("Togo","Togo","TG","TGO",768,184),
   TO("Tonga","Tonga","TO","TON",776,185),
   TT("Trinidad and Tobago","Trinidad and Tobago","TT","TTO",780,186),
   TN("Tunisia","Tunisia","TN","TUN",788,187),
   TM("Turkmenistan","Turkmenistan","TM","TKM",795,188),
   TV("Tuvalu","Tuvalu","TV","TUV",798,189),
   UG("Uganda","Uganda","UG","UGA",800,190),
   UY("Uruguay","Uruguay","UY","URY",858,191),
   UZ("Uzbekistan","Uzbekistan","UZ","UZB",860,192),
   VU("Vanuatu","Vanuatu","VU","VUT",548,193),
   VN("Vietnam","Vietnam","VN","VNM",704,194),
   YE("Yemen","Yemen","YE","YEM",887,195),
   ZM("Zambia","Zambia","ZM","ZMB",894,196),
   ZW("Zimbabwe","Zimbabwe","ZW","ZWE",716,197),
   GE("Georgia","Georgia","GE","GEO",268,198),
   GG("Guernsey","Guernsey","GG","GGY",0,199),
   JE("Jersey","Jersey","JE","JEY",0,200),
   SY("Syria","Syria","SY","SYR",760,201),
   CF("Central African Republic","Central African Republic","CF","CAF",140,202),
   KM("Comoros","Comoros","KM","COM",174,203),
   GQ("Equatorial Guinea","Equatorial Guinea","GQ","GNQ",226,204),
   ER("Eritrea","Eritrea","ER","ERI",232,205),
   GW("Guinea-Bissau","Guinea-Bissau","GW","GNB",624,206),
   LR("Liberia","Liberia","LR","LBR",430,207),
   ML("Mali","Mali","ML","MLI",466,208),
   RE("Reunion","Reunion","RE","REU",638,209),
   SH("Saint Helena","Saint Helena","SH","SHN",654,210),
   ST("Sao Tome and Principe","Sao Tome and Principe","ST","STP",678,211),
   SL("Sierra Leone","Sierra Leone","SL","SLE",694,212),
   SZ("Swaziland","Swaziland","SZ","SWZ",748,213),
   AI("Anguilla","Anguilla","AI","AIA",660,214),
   MS("Montserrat","Montserrat","MS","MSR",500,215),
   VG("Virgin Islands, British","Virgin Islands, British","VG","VGB",92,216),
   VI("Virgin Islands, U.S.","Virgin Islands, U.S.","VI","VIR",850,217),
   PM("St. Pierre and Miquelon","St. Pierre and Miquelon","PM","SPM",666,218),
   BT("Bhutan","Bhutan","BT","BTN",64,219),
   AS("American Samoa","American Samoa","AS","ASM",16,220),
   GU("Guam","Guam","GU","GUM",316,221),
   WF("Wallis and Futuna","Wallis and Futuna","WF","WLF",876,222),
   RS("Serbia","Serbia","RS","SRB",0,223),
   ME("Montenegro","Montenegro","ME","MNE",499,224),
   CD("Congo, Democratic Republic of the","Congo, Democratic Republic of the","CD","COD",180,225),
   IM("Isle of Man","Isle of Man","IM","IMN",0,226),
   BV("Bouvet Island","Bouvet Island","BV","BVT",74,227),
   TF("French Southern Territories","French Southern Territories","TF","ATF",260,228),
   EH("Western Sahara","Western Sahara","EH","ESH",732,229),
   A1("Anonymous Proxy","Anonymous Proxy","A1","0",0,230),
   A2("Satellite Provider","Satellite Provider","A2","0",0,231),
   AP("Asia/Pacific Region","Asia/Pacific Region","AP","0",0,232),
   AQ("Antarctica","Antarctica","AQ","ATA",10,233),
   AX("Aland Islands","Aland Islands","AX","ALA",248,234),
   CK("Cook Islands","Cook Islands","CK","COK",184,235),
   EU("Europe","Europe","EU","0",0,236),
   FM("Micronesia, Federated States of","Micronesia, Federated States of","FM","FSM",583,237),
   HM("Heard Island and McDonald Islands","Heard Island and McDonald Islands","HM","HMD",334,238),
   IO("British Indian Ocean Territory","British Indian Ocean Territory","IO","IOT",86,239),
   KI("Kiribati","Kiribati","KI","KIR",296,240),
   MH("Marshall Islands","Marshall Islands","MH","MHL",584,241),
   MP("Northern Mariana Islands","Northern Mariana Islands","MP","MNP",580,242),
   NF("Norfolk Island","Norfolk Island","NF","NFK",574,243),
   NR("Nauru","Nauru","NR","NRU",520,244),
   NU("Niue","Niue","NU","NIU",570,245),
   PS("Palestinian Territory, Occupied","Palestinian Territory, Occupied","PS","PSE",275,246),
   PW("Palau","Palau","PW","PLW",585,247),
   SB("Solomon Islands","Solomon Islands","SB","SLB",90,248),
   TC("Turks and Caicos Islands","Turks and Caicos Islands","TC","TCA",796,249),
   TK("Tokelau","Tokelau","TK","TKL",772,250),
   WS("Samoa","Samoa","WS","WSM",882,251);
"""

json_data_en = """
[["United Kingdom","United Kingdom"],["Ireland","Ireland"],["United States of America","United States of America"],["Canada","Canada"],["Afghanistan","Afghanistan"],["Aland Islands","Aland Islands"],["Albania","Albania"],["Algeria","Algeria"],["American Samoa","American Samoa"],["Andorra","Andorra"],["Angola","Angola"],["Anguilla","Anguilla"],["Antarctica","Antarctica"],["Antigua and Barbuda","Antigua and Barbuda"],["Argentina","Argentina"],["Armenia","Armenia"],["Aruba","Aruba"],["Australia","Australia"],["Austria","Austria"],["Azerbaijan","Azerbaijan"],["Bahamas","Bahamas"],["Bahrain","Bahrain"],["Bangladesh","Bangladesh"],["Barbados","Barbados"],["Belarus","Belarus"],["Belgium","Belgium"],["Belize","Belize"],["Benin","Benin"],["Bermuda","Bermuda"],["Bhutan","Bhutan"],["Bolivia","Bolivia"],["Bosnia and Herzegovina","Bosnia and Herzegovina"],["Botswana","Botswana"],["Bouvet Island","Bouvet Island"],["Brazil","Brazil"],["British Indian Ocean Territory","British Indian Ocean Territory"],["Brunei Darussalam","Brunei Darussalam"],["Bulgaria","Bulgaria"],["Burkina Faso","Burkina Faso"],["Burundi","Burundi"],["Cambodia","Cambodia"],["Cameroon","Cameroon"],["Canada","Canada"],["Cape Verde","Cape Verde"],["Cayman Islands","Cayman Islands"],["Central African Republic","Central African Republic"],["Chad","Chad"],["Chile","Chile"],["China","China"],["Colombia","Colombia"],["Comoros","Comoros"],["Congo","Congo"],["Congo, Democratic Republic of the","Congo, Democratic Republic of the"],["Cook Islands","Cook Islands"],["Costa Rica","Costa Rica"],["Croatia","Croatia"],["Cuba","Cuba"],["Cyprus","Cyprus"],["Czech Republic","Czech Republic"],["Denmark","Denmark"],["Djibouti","Djibouti"],["Dominica","Dominica"],["Dominican Republic","Dominican Republic"],["Ecuador","Ecuador"],["Egypt","Egypt"],["El Salvador","El Salvador"],["Equatorial Guinea","Equatorial Guinea"],["Eritrea","Eritrea"],["Estonia","Estonia"],["Ethiopia","Ethiopia"],["Falkland Islands","Falkland Islands"],["Faroe Islands","Faroe Islands"],["Fiji","Fiji"],["Finland","Finland"],["France","France"],["French Guiana","French Guiana"],["French Polynesia","French Polynesia"],["French Southern Territories","French Southern Territories"],["Gabon","Gabon"],["Gambia","Gambia"],["Georgia","Georgia"],["Germany","Germany"],["Ghana","Ghana"],["Gibraltar","Gibraltar"],["Greece","Greece"],["Greenland","Greenland"],["Grenada","Grenada"],["Guadeloupe","Guadeloupe"],["Guam","Guam"],["Guatemala","Guatemala"],["Guernsey","Guernsey"],["Guinea","Guinea"],["Guinea-Bissau","Guinea-Bissau"],["Guyana","Guyana"],["Haiti","Haiti"],["Heard Island and McDonald Islands","Heard Island and McDonald Islands"],["Honduras","Honduras"],["Hong Kong","Hong Kong"],["Hungary","Hungary"],["Iceland","Iceland"],["India","India"],["Indonesia","Indonesia"],["Iran","Iran"],["Iraq","Iraq"],["Ireland","Ireland"],["Isle of Man","Isle of Man"],["Israel","Israel"],["Italy","Italy"],["Ivory Coast","Ivory Coast"],["Jamaica","Jamaica"],["Japan","Japan"],["Jersey","Jersey"],["Jordan","Jordan"],["Kazakhstan","Kazakhstan"],["Kenya","Kenya"],["Kiribati","Kiribati"],["Korea, North","Korea, North"],["Korea, South","Korea, South"],["Kuwait","Kuwait"],["Kyrgyzstan","Kyrgyzstan"],["Laos","Laos"],["Latvia","Latvia"],["Lebanon","Lebanon"],["Lesotho","Lesotho"],["Liberia","Liberia"],["Libya","Libya"],["Liechtenstein","Liechtenstein"],["Lithuania","Lithuania"],["Luxembourg","Luxembourg"],["Macao","Macao"],["Macedonia","Macedonia"],["Madagascar","Madagascar"],["Malawi","Malawi"],["Malaysia","Malaysia"],["Maldives","Maldives"],["Mali","Mali"],["Malta","Malta"],["Marshall Islands","Marshall Islands"],["Martinique","Martinique"],["Mauritania","Mauritania"],["Mauritius","Mauritius"],["Mayotte","Mayotte"],["Mexico","Mexico"],["Micronesia, Federated States of","Micronesia, Federated States of"],["Moldova","Moldova"],["Monaco","Monaco"],["Mongolia","Mongolia"],["Montenegro","Montenegro"],["Montserrat","Montserrat"],["Morocco","Morocco"],["Mozambique","Mozambique"],["Myanmar","Myanmar"],["Namibia","Namibia"],["Nauru","Nauru"],["Nepal","Nepal"],["Netherlands","Netherlands"],["Netherlands Antilles","Netherlands Antilles"],["New Caledonia","New Caledonia"],["New Zealand","New Zealand"],["Nicaragua","Nicaragua"],["Niger","Niger"],["Nigeria","Nigeria"],["Niue","Niue"],["Norfolk Island","Norfolk Island"],["Northern Mariana Islands","Northern Mariana Islands"],["Norway","Norway"],["Oman","Oman"],["Pakistan","Pakistan"],["Palau","Palau"],["Palestinian Territory, Occupied","Palestinian Territory, Occupied"],["Panama","Panama"],["Papua New Guinea","Papua New Guinea"],["Paraguay","Paraguay"],["Peru","Peru"],["Philippines","Philippines"],["Poland","Poland"],["Portugal","Portugal"],["Puerto Rico","Puerto Rico"],["Qatar","Qatar"],["Reunion","R&#233;union"],["Romania","Romania"],["Russia","Russia"],["Rwanda","Rwanda"],["Saint Helena","Saint Helena"],["Samoa","Samoa"],["San Marino","San Marino"],["Sao Tome and Principe","Sao Tome and Principe"],["Saudi Arabia","Saudi Arabia"],["Senegal","Senegal"],["Serbia","Serbia"],["Seychelles","Seychelles"],["Sierra Leone","Sierra Leone"],["Singapore","Singapore"],["Slovakia","Slovakia"],["Slovenia","Slovenia"],["Solomon Islands","Solomon Islands"],["Somalia","Somalia"],["South Africa","South Africa"],["Spain","Spain"],["Sri Lanka","Sri Lanka"],["St. Kitts and Nevis","St. Kitts and Nevis"],["St. Lucia","St. Lucia"],["St. Pierre and Miquelon","St. Pierre and Miquelon"],["St. Vincent and the Grenadines","St. Vincent and the Grenadines"],["Sudan","Sudan"],["Suriname","Suriname"],["Swaziland","Swaziland"],["Sweden","Sweden"],["Switzerland","Switzerland"],["Syria","Syria"],["Tahiti","Tahiti"],["Taiwan","Taiwan"],["Tajikistan","Tajikistan"],["Tanzania","Tanzania"],["Thailand","Thailand"],["Togo","Togo"],["Tokelau","Tokelau"],["Tonga","Tonga"],["Trinidad and Tobago","Trinidad and Tobago"],["Tunisia","Tunisia"],["Turkey","Turkey"],["Turkmenistan","Turkmenistan"],["Turks and Caicos Islands","Turks and Caicos Islands"],["Tuvalu","Tuvalu"],["Uganda","Uganda"],["Ukraine","Ukraine"],["United Arab Emirates","United Arab Emirates"],["United Kingdom","United Kingdom"],["United States of America","United States of America"],["Uruguay","Uruguay"],["U.S. Minor Outlying Islands","U.S. Minor Outlying Islands"],["Uzbekistan","Uzbekistan"],["Vanuatu","Vanuatu"],["Vatican City","Vatican City"],["Venezuela","Venezuela"],["Vietnam","Vietnam"],["Virgin Islands, British","Virgin Islands, British"],["Virgin Islands, U.S.","Virgin Islands, U.S."],["Wallis and Futuna","Wallis and Futuna"],["Western Sahara","Western Sahara"],["Yemen","Yemen"],["Zambia","Zambia"],["Zimbabwe","Zimbabwe"]]
"""
json_data_en_gb = """
[["United Kingdom","United Kingdom"],["Ireland","Ireland"],["United States of America","United States of America"],["Canada","Canada"],["Afghanistan","Afghanistan"],["Aland Islands","Aland Islands"],["Albania","Albania"],["Algeria","Algeria"],["American Samoa","American Samoa"],["Andorra","Andorra"],["Angola","Angola"],["Anguilla","Anguilla"],["Antarctica","Antarctica"],["Antigua and Barbuda","Antigua and Barbuda"],["Argentina","Argentina"],["Armenia","Armenia"],["Aruba","Aruba"],["Australia","Australia"],["Austria","Austria"],["Azerbaijan","Azerbaijan"],["Bahamas","Bahamas"],["Bahrain","Bahrain"],["Bangladesh","Bangladesh"],["Barbados","Barbados"],["Belarus","Belarus"],["Belgium","Belgium"],["Belize","Belize"],["Benin","Benin"],["Bermuda","Bermuda"],["Bhutan","Bhutan"],["Bolivia","Bolivia"],["Bosnia and Herzegovina","Bosnia and Herzegovina"],["Botswana","Botswana"],["Bouvet Island","Bouvet Island"],["Brazil","Brazil"],["British Indian Ocean Territory","British Indian Ocean Territory"],["Brunei Darussalam","Brunei Darussalam"],["Bulgaria","Bulgaria"],["Burkina Faso","Burkina Faso"],["Burundi","Burundi"],["Cambodia","Cambodia"],["Cameroon","Cameroon"],["Canada","Canada"],["Cape Verde","Cape Verde"],["Cayman Islands","Cayman Islands"],["Central African Republic","Central African Republic"],["Chad","Chad"],["Chile","Chile"],["China","China"],["Colombia","Colombia"],["Comoros","Comoros"],["Congo","Congo"],["Congo, Democratic Republic of the","Congo, Democratic Republic of the"],["Cook Islands","Cook Islands"],["Costa Rica","Costa Rica"],["Croatia","Croatia"],["Cuba","Cuba"],["Cyprus","Cyprus"],["Czech Republic","Czech Republic"],["Denmark","Denmark"],["Djibouti","Djibouti"],["Dominica","Dominica"],["Dominican Republic","Dominican Republic"],["Ecuador","Ecuador"],["Egypt","Egypt"],["El Salvador","El Salvador"],["Equatorial Guinea","Equatorial Guinea"],["Eritrea","Eritrea"],["Estonia","Estonia"],["Ethiopia","Ethiopia"],["Falkland Islands","Falkland Islands"],["Faroe Islands","Faroe Islands"],["Fiji","Fiji"],["Finland","Finland"],["France","France"],["French Guiana","French Guiana"],["French Polynesia","French Polynesia"],["French Southern Territories","French Southern Territories"],["Gabon","Gabon"],["Gambia","Gambia"],["Georgia","Georgia"],["Germany","Germany"],["Ghana","Ghana"],["Gibraltar","Gibraltar"],["Greece","Greece"],["Greenland","Greenland"],["Grenada","Grenada"],["Guadeloupe","Guadeloupe"],["Guam","Guam"],["Guatemala","Guatemala"],["Guernsey","Guernsey"],["Guinea","Guinea"],["Guinea-Bissau","Guinea-Bissau"],["Guyana","Guyana"],["Haiti","Haiti"],["Heard Island and McDonald Islands","Heard Island and McDonald Islands"],["Honduras","Honduras"],["Hong Kong","Hong Kong"],["Hungary","Hungary"],["Iceland","Iceland"],["India","India"],["Indonesia","Indonesia"],["Iran","Iran"],["Iraq","Iraq"],["Ireland","Ireland"],["Isle of Man","Isle of Man"],["Israel","Israel"],["Italy","Italy"],["Ivory Coast","Ivory Coast"],["Jamaica","Jamaica"],["Japan","Japan"],["Jersey","Jersey"],["Jordan","Jordan"],["Kazakhstan","Kazakhstan"],["Kenya","Kenya"],["Kiribati","Kiribati"],["Korea, North","Korea, North"],["Korea, South","Korea, South"],["Kuwait","Kuwait"],["Kyrgyzstan","Kyrgyzstan"],["Laos","Laos"],["Latvia","Latvia"],["Lebanon","Lebanon"],["Lesotho","Lesotho"],["Liberia","Liberia"],["Libya","Libya"],["Liechtenstein","Liechtenstein"],["Lithuania","Lithuania"],["Luxembourg","Luxembourg"],["Macao","Macao"],["Macedonia","Macedonia"],["Madagascar","Madagascar"],["Malawi","Malawi"],["Malaysia","Malaysia"],["Maldives","Maldives"],["Mali","Mali"],["Malta","Malta"],["Marshall Islands","Marshall Islands"],["Martinique","Martinique"],["Mauritania","Mauritania"],["Mauritius","Mauritius"],["Mayotte","Mayotte"],["Mexico","Mexico"],["Micronesia, Federated States of","Micronesia, Federated States of"],["Moldova","Moldova"],["Monaco","Monaco"],["Mongolia","Mongolia"],["Montenegro","Montenegro"],["Montserrat","Montserrat"],["Morocco","Morocco"],["Mozambique","Mozambique"],["Myanmar","Myanmar"],["Namibia","Namibia"],["Nauru","Nauru"],["Nepal","Nepal"],["Netherlands","Netherlands"],["Netherlands Antilles","Netherlands Antilles"],["New Caledonia","New Caledonia"],["New Zealand","New Zealand"],["Nicaragua","Nicaragua"],["Niger","Niger"],["Nigeria","Nigeria"],["Niue","Niue"],["Norfolk Island","Norfolk Island"],["Northern Mariana Islands","Northern Mariana Islands"],["Norway","Norway"],["Oman","Oman"],["Pakistan","Pakistan"],["Palau","Palau"],["Palestinian Territory, Occupied","Palestinian Territory, Occupied"],["Panama","Panama"],["Papua New Guinea","Papua New Guinea"],["Paraguay","Paraguay"],["Peru","Peru"],["Philippines","Philippines"],["Poland","Poland"],["Portugal","Portugal"],["Puerto Rico","Puerto Rico"],["Qatar","Qatar"],["Reunion","R&#233;union"],["Romania","Romania"],["Russia","Russia"],["Rwanda","Rwanda"],["Saint Helena","Saint Helena"],["Samoa","Samoa"],["San Marino","San Marino"],["Sao Tome and Principe","Sao Tome and Principe"],["Saudi Arabia","Saudi Arabia"],["Senegal","Senegal"],["Serbia","Serbia"],["Seychelles","Seychelles"],["Sierra Leone","Sierra Leone"],["Singapore","Singapore"],["Slovakia","Slovakia"],["Slovenia","Slovenia"],["Solomon Islands","Solomon Islands"],["Somalia","Somalia"],["South Africa","South Africa"],["Spain","Spain"],["Sri Lanka","Sri Lanka"],["St. Kitts and Nevis","St. Kitts and Nevis"],["St. Lucia","St. Lucia"],["St. Pierre and Miquelon","St. Pierre and Miquelon"],["St. Vincent and the Grenadines","St. Vincent and the Grenadines"],["Sudan","Sudan"],["Suriname","Suriname"],["Swaziland","Swaziland"],["Sweden","Sweden"],["Switzerland","Switzerland"],["Syria","Syria"],["Tahiti","Tahiti"],["Taiwan","Taiwan"],["Tajikistan","Tajikistan"],["Tanzania","Tanzania"],["Thailand","Thailand"],["Togo","Togo"],["Tokelau","Tokelau"],["Tonga","Tonga"],["Trinidad and Tobago","Trinidad and Tobago"],["Tunisia","Tunisia"],["Turkey","Turkey"],["Turkmenistan","Turkmenistan"],["Turks and Caicos Islands","Turks and Caicos Islands"],["Tuvalu","Tuvalu"],["Uganda","Uganda"],["Ukraine","Ukraine"],["United Arab Emirates","United Arab Emirates"],["United Kingdom","United Kingdom"],["United States of America","United States of America"],["Uruguay","Uruguay"],["U.S. Minor Outlying Islands","U.S. Minor Outlying Islands"],["Uzbekistan","Uzbekistan"],["Vanuatu","Vanuatu"],["Vatican City","Vatican City"],["Venezuela","Venezuela"],["Vietnam","Vietnam"],["Virgin Islands, British","Virgin Islands, British"],["Virgin Islands, U.S.","Virgin Islands, U.S."],["Wallis and Futuna","Wallis and Futuna"],["Western Sahara","Western Sahara"],["Yemen","Yemen"],["Zambia","Zambia"],["Zimbabwe","Zimbabwe"]]
"""
json_data_fr = """
[["France","France"],["Belgium","Belgique"],["Switzerland","Suisse"],["Afghanistan","Afghanistan"],["South Africa","Afrique du Sud"],["Albania","Albanie"],["Algeria","Alg&#233;rie"],["Germany","Allemagne"],["Andorra","Andorre"],["Angola","Angola"],["Anguilla","Anguilla"],["Antarctica","Antarctique"],["Antigua and Barbuda","Antigua-et-Barbuda"],["Netherlands Antilles","Antilles n&#233;erlandaises"],["Saudi Arabia","Arabie saoudite"],["Argentina","Argentine"],["Armenia","Arm&#233;nie"],["Aruba","Aruba"],["Australia","Australie"],["Austria","Autriche"],["Azerbaijan","Azerba&#239;djan"],["Bahamas","Bahamas"],["Bahrain","Bahre&#239;n"],["Bangladesh","Bangladesh"],["Barbados","Barbade"],["Belgium","Belgique"],["Belize","Belize"],["Benin","B&#233;nin"],["Bermuda","Bermudes"],["Bhutan","Bhoutan"],["Belarus","Bi&#233;lorussie"],["Bolivia","Bolivie"],["Bosnia and Herzegovina","Bosnie Herz&#233;govine"],["Botswana","Botswana"],["Brazil","Br&#233;sil"],["Brunei Darussalam","Brun&#233;i Darussalam"],["Bulgaria","Bulgarie"],["Burkina Faso","Burkina Faso"],["Burundi","Burundi"],["Cambodia","Cambodge"],["Cameroon","Cameroun"],["Canada","Canada"],["Cape Verde","Cap-Vert"],["Chile","Chili"],["China","Chine"],["Cyprus","Chypre"],["Vatican City","Cit&#233; du Vatican"],["Colombia","Colombie"],["Comoros","Comores"],["Congo","Congo"],["Korea, North","Cor&#233;e du Nord"],["Korea, South","Cor&#233;e du Sud"],["Costa Rica","Costa Rica"],["Ivory Coast","C&#244;te d'Ivoire"],["Croatia","Croatie"],["Cuba","Cuba"],["Denmark","Danemark"],["Djibouti","Djibouti"],["Dominica","Dominique"],["Egypt","Egypte"],["United Arab Emirates","Emirats Arabes Unis"],["Ecuador","Equateur"],["Eritrea","Erythr&#233;e"],["Spain","Espagne"],["Estonia","Estonie"],["Micronesia, Federated States of","Etats f&#233;d&#233;r&#233;s de Micron&#233;sie"],["United States of America","Etats-Unis"],["Ethiopia","Ethiopie"],["Finland","Finlande"],["France","France"],["Gabon","Gabon"],["Gambia","Gambie"],["Georgia","G&#233;orgie"],["Ghana","Ghana"],["Gibraltar","Gibraltar"],["Greece","Gr&#232;ce"],["Grenada","Grenade"],["Greenland","Groenland"],["Guadeloupe","Guadeloupe"],["Guam","Guam"],["Guatemala","Guatemala"],["Guernsey","Guernesey"],["Guinea","Guin&#233;e"],["Guinea-Bissau","Guin&#233;e-Bissau"],["Equatorial Guinea","Guin&#233;e Equatoriale"],["Guyana","Guyane"],["French Guiana","Guyane fran&#231;aise"],["Haiti","Ha&#239;ti"],["Honduras","Honduras"],["Hong Kong","Hong Kong"],["Hungary","Hongrie"],["Bouvet Island","Ile Bouvet"],["Isle of Man","Ile de Man"],["Heard Island and McDonald Islands","Ile Heard et les &#238;les McDonald"],["Mauritius","Ile Maurice"],["Norfolk Island","Ile Norfolk"],["Aland Islands","Iles Aland"],["Cayman Islands","Iles Ca&#239;mans"],["Cook Islands","Iles Cook"],["Falkland Islands","Iles Falkland"],["Faroe Islands","Iles F&#233;ro&#233;"],["Fiji","Iles Fidji"],["Northern Mariana Islands","Iles Mariannes du Nord"],["Marshall Islands","Iles Marshall"],["Solomon Islands","Iles Salomon"],["Turks and Caicos Islands","Iles Turques et Ca&#239;ques"],["Virgin Islands, U.S.","Iles Vierges am&#233;ricaines"],["Virgin Islands, British","Iles Vierges britanniques"],["India","Inde"],["Indonesia","Indon&#233;sie"],["Iraq","Irak"],["Iran","Iran"],["Ireland","Irlande"],["Iceland","Islande"],["Israel","Isra&#235;l"],["Italy","Italie"],["Jamaica","Jama&#239;que"],["Japan","Japon"],["Jersey","Jersey"],["Jordan","Jordanie"],["Kazakhstan","Kazakhstan"],["Kenya","Kenya"],["Kyrgyzstan","Kirghizstan"],["Kiribati","Kiribati"],["Kuwait","Kowe&#239;t"],["Laos","Laos"],["Lesotho","Lesotho"],["Latvia","Lettonie"],["Lebanon","Liban"],["Liberia","Lib&#233;ria"],["Libya","Libye"],["Liechtenstein","Liechtenstein"],["Lithuania","Lituanie"],["Luxembourg","Luxembourg"],["Macao","Macao"],["Macedonia","Mac&#233;doine"],["Madagascar","Madagascar"],["Malaysia","Malaisie"],["Malawi","Malawi"],["Maldives","Maldives"],["Mali","Mali"],["Malta","Malte"],["Morocco","Maroc"],["Martinique","Martinique"],["Mauritania","Mauritanie"],["Mayotte","Mayotte"],["Mexico","Mexique"],["Moldova","Moldavie"],["Monaco","Monaco"],["Mongolia","Mongolie"],["Montenegro","Mont&#233;n&#233;gro"],["Montserrat","Montserrat"],["Mozambique","Mozambique"],["Myanmar","Myanmar"],["Namibia","Namibie"],["Nauru","Nauru"],["Nepal","N&#233;pal"],["Nicaragua","Nicaragua"],["Niger","Niger"],["Nigeria","Nigeria"],["Niue","Niu&#233;"],["Norway","Norv&#232;ge"],["New Caledonia","Nouvelle Cal&#233;donie"],["New Zealand","Nouvelle-Z&#233;lande"],["Oman","Oman"],["Uganda","Ouganda"],["Uzbekistan","Ouzb&#233;kistan"],["Pakistan","Pakistan"],["Palau","Palaos"],["Panama","Panama"],["Papua New Guinea","Papouasie-Nouvelle-Guin&#233;e"],["Paraguay","Paraguay"],["Netherlands","Pays-Bas"],["Peru","P&#233;rou"],["U.S. Minor Outlying Islands","Petites &#238;les voisines des E-U"],["Philippines","Philippines"],["Poland","Pologne"],["French Polynesia","Polyn&#233;sie fran&#231;aise"],["Puerto Rico","Porto Rico"],["Portugal","Portugal"],["Qatar","Qatar"],["Central African Republic","R&#233;publique centrafricaine"],["Congo, Democratic Republic of the","R&#233;publique D&#233;mocratique du Congo"],["Dominican Republic","R&#233;publique dominicaine"],["Czech Republic","R&#233;publique tch&#232;que"],["Reunion","R&#233;union"],["Romania","Roumanie"],["United Kingdom","Royaume-Uni"],["Russia","Russie"],["Rwanda","Rwanda"],["Western Sahara","Sahara occidental"],["St. Lucia","Sainte-Lucie"],["Saint Helena","Saint H&#233;l&#232;ne"],["San Marino","Saint-Marin"],["St. Vincent and the Grenadines","Saint-Vincent-et-Grenadines"],["El Salvador","Salvador"],["Samoa","Samoa"],["American Samoa","Samoa am&#233;ricaines"],["Sao Tome and Principe","S&#227;o Tom&#233; et Principe"],["Senegal","S&#233;n&#233;gal"],["Serbia","Serbie"],["Seychelles","Seychelles"],["Sierra Leone","Sierra Leone"],["Singapore","Singapour"],["Slovakia","Slovaquie"],["Slovenia","Slov&#233;nie"],["Somalia","Somalie"],["Sudan","Soudan"],["Sri Lanka","Sri Lanka"],["St. Kitts and Nevis","St. Kitts-et-Nevis"],["St. Pierre and Miquelon","St. Pierre et Miquelon"],["Sweden","Su&#232;de"],["Switzerland","Suisse"],["Suriname","Surinam"],["Swaziland","Swaziland"],["Syria","Syrie"],["Tajikistan","Tadjikistan"],["Tahiti","Tahiti"],["Taiwan","Ta&#239;wan"],["Tanzania","Tanzanie"],["Chad","Tchad"],["French Southern Territories","Terres australes fran&#231;aises"],["British Indian Ocean Territory","Territoire britannique de l'Oc&#233;an Indien"],["Palestinian Territory, Occupied","Territoires palestiniens occup&#233;s"],["Thailand","Tha&#239;lande"],["Togo","Togo"],["Tokelau","Tokelau"],["Tonga","Tonga"],["Trinidad and Tobago","Trinit&#233;-et-Tobago"],["Tunisia","Tunisie"],["Turkmenistan","Turkm&#233;nistan"],["Turkey","Turquie"],["Tuvalu","Tuvalu"],["Ukraine","Ukraine"],["Uruguay","Uruguay"],["Vanuatu","Vanuatu"],["Venezuela","Venezuela"],["Vietnam","Vietnam"],["Wallis and Futuna","Wallis et Futuna"],["Yemen","Y&#233;men"],["Zambia","Zambie"],["Zimbabwe","Zimbabwe"]]
"""
json_data_de = """
[["Germany","Deutschland"],["Austria","&#214;sterreich"],["Switzerland","Schweiz"],["Afghanistan","Afghanistan"],["Egypt","&#196;gypten"],["Aland Islands","Aland-Inseln"],["Albania","Albanien"],["Algeria","Algerien"],["Virgin Islands, U.S.","Amerikanische Jungferninseln"],["U.S. Minor Outlying Islands","Amerikanisch-Ozeanien"],["American Samoa","Amerikanisch-Samoa"],["Andorra","Andorra"],["Angola","Angola"],["Anguilla","Anguilla"],["Antarctica","Antarktis"],["Antigua and Barbuda","Antigua und Barbuda"],["Equatorial Guinea","&#196;quatorialguinea"],["Argentina","Argentinien"],["Armenia","Armenien"],["Aruba","Aruba"],["Azerbaijan","Aserbeidschan"],["Ethiopia","&#196;thiopien"],["Australia","Australien"],["Bahamas","Bahamas"],["Bahrain","Bahrain"],["Bangladesh","Bangladesch"],["Barbados","Barbados"],["Belgium","Belgien"],["Belize","Belize"],["Benin","Benin"],["Bermuda","Bermudas"],["Bhutan","Bhutan"],["Bolivia","Bolivien"],["Bosnia and Herzegovina","Bosnien-Herzegowina"],["Botswana","Botswana"],["Bouvet Island","Bouvetinsel"],["Brazil","Brasilien"],["Virgin Islands, British","Britische Jungferninseln"],["British Indian Ocean Territory","Britisches Territorium im Indischen Ozean"],["Brunei Darussalam","Brunei Darussalam"],["Bulgaria","Bulgarien"],["Burkina Faso","Burkina Faso"],["Burundi","Burundi"],["Chile","Chile"],["China","China"],["Cook Islands","Cookinseln"],["Costa Rica","Costa Rica"],["Denmark","D&#228;nemark"],["Germany","Deutschland"],["Dominica","Dominica"],["Dominican Republic","Dominikanische Republik"],["Djibouti","Dschibuti"],["Ecuador","Ecuador"],["Ivory Coast","Elfenbeink&#252;ste"],["El Salvador","El Salvador"],["Eritrea","Eritrea"],["Estonia","Estland"],["Falkland Islands","Falklandinseln"],["Faroe Islands","F&#228;r&#246;er Inseln"],["Fiji","Fidschiinseln"],["Finland","Finnland"],["France","Frankreich"],["French Southern Territories","Franz&#246;sische S&#252;d- und Antarktisgebiete"],["French Guiana","Franz&#246;sisch-Guayana"],["French Polynesia","Franz&#246;sisch-Polynesien"],["Gabon","Gabun"],["Gambia","Gambia"],["Georgia","Georgien"],["Ghana","Ghana"],["Gibraltar","Gibraltar"],["Grenada","Grenada"],["Greece","Griechenland"],["Greenland","Gr&#246;nland"],["United Kingdom","Gro&#223;britannien"],["Guadeloupe","Guadeloupe"],["Guam","Guam"],["Guatemala","Guatemala"],["Guernsey","Guernsey"],["Guinea","Guinea"],["Guinea-Bissau","Guinea-Bissau"],["Guyana","Guyana"],["Haiti","Haiti"],["Heard Island and McDonald Islands","Heard und McDonaldinseln"],["Honduras","Honduras"],["Hong Kong","Hongkong"],["India","Indien"],["Indonesia","Indonesien"],["Iraq","Irak"],["Iran","Iran"],["Ireland","Irland"],["Iceland","Island"],["Isle of Man","Isle of Man"],["Israel","Israel"],["Italy","Italien"],["Jamaica","Jamaika"],["Japan","Japan"],["Yemen","Jemen"],["Jersey","Jersey"],["Jordan","Jordanien"],["Cayman Islands","Kaimaninseln"],["Cambodia","Kambodscha"],["Cameroon","Kamerun"],["Canada","Kanada"],["Cape Verde","Kap Verde"],["Kazakhstan","Kasachstan"],["Qatar","Katar"],["Kenya","Kenia"],["Kyrgyzstan","Kirgistan"],["Kiribati","Kiribati"],["Colombia","Kolumbien"],["Comoros","Komoren"],["Congo","Kongo"],["Congo, Democratic Republic of the","Kongo, demokratische Republik"],["Korea, North","Korea (Nord)"],["Korea, South","Korea (S&#252;d)"],["Croatia","Kroatien"],["Cuba","Kuba"],["Kuwait","Kuwait"],["Laos","Laos"],["Lesotho","Lesotho"],["Latvia","Lettland"],["Lebanon","Libanon"],["Liberia","Liberia"],["Libya","Libyen"],["Liechtenstein","Liechtenstein"],["Lithuania","Litauen"],["Luxembourg","Luxemburg"],["Madagascar","Madagaskar"],["Macao","Makao"],["Malawi","Malawi"],["Malaysia","Malaysia"],["Maldives","Malediven"],["Mali","Mali"],["Malta","Malta"],["Morocco","Marokko"],["Marshall Islands","Marshallinseln"],["Martinique","Martinique"],["Mauritania","Mauretanien"],["Mauritius","Mauritius"],["Mayotte","Mayotte"],["Macedonia","Mazedonien"],["Mexico","Mexiko"],["Micronesia, Federated States of","Mikronesien, F&#246;derierte Staaten von"],["Moldova","Moldawien"],["Monaco","Monaco"],["Mongolia","Mongolei"],["Montenegro","Montenegro"],["Montserrat","Montserrat"],["Mozambique","Mosambik"],["Myanmar","Myanmar"],["Namibia","Namibia"],["Nauru","Nauru"],["Nepal","Nepal"],["New Caledonia","Neukaledonien"],["New Zealand","Neuseeland"],["Nicaragua","Nicaragua"],["Netherlands","Niederlande"],["Netherlands Antilles","Niederl&#228;ndische Antillen"],["Niger","Niger"],["Nigeria","Nigeria"],["Niue","Niue"],["Northern Mariana Islands","N&#246;rdliche Marianen"],["Norfolk Island","Norfolkinsel"],["Norway","Norwegen"],["Oman","Oman"],["Austria","&#214;sterreich"],["Pakistan","Pakistan"],["Palestinian Territory, Occupied","Pal&#228;stinensische Autonomiegebiete"],["Palau","Palau"],["Panama","Panama"],["Papua New Guinea","Papua-Neuguinea"],["Paraguay","Paraguay"],["Peru","Peru"],["Philippines","Philippinen"],["Poland","Polen"],["Portugal","Portugal"],["Puerto Rico","Puerto Rico"],["Reunion","R&#233;union"],["Rwanda","Ruanda"],["Romania","Rum&#228;nien"],["Russia","Russland"],["Saint Helena","Saint Helena"],["Solomon Islands","Salomonen"],["Zambia","Sambia"],["Samoa","Samoa"],["San Marino","San Marino"],["Sao Tome and Principe","Sao Tome und Principe"],["Saudi Arabia","Saudi-Arabien"],["Sweden","Schweden"],["Switzerland","Schweiz"],["Senegal","Senegal"],["Serbia","Serbien"],["Seychelles","Seychellen"],["Sierra Leone","Sierra Leone"],["Zimbabwe","Simbabwe"],["Singapore","Singapur"],["Slovakia","Slowakei"],["Slovenia","Slowenien"],["Somalia","Somalia"],["Spain","Spanien"],["Sri Lanka","Sri Lanka"],["St. Kitts and Nevis","St. Kitts und Nevis"],["St. Lucia","St. Lucia"],["St. Pierre and Miquelon","St. Pierre und Miquelon"],["St. Vincent and the Grenadines","St. Vincent und die Grenadinen"],["South Africa","S&#252;dafrika"],["Sudan","Sudan"],["Suriname","Surinam"],["Swaziland","Swaziland"],["Syria","Syrien"],["Tajikistan","Tadschikistan"],["Tahiti","Tahiti"],["Taiwan","Taiwan"],["Tanzania","Tansania"],["Thailand","Thailand"],["Togo","Togo"],["Tokelau","Tokelau"],["Tonga","Tonga"],["Trinidad and Tobago","Trinidad und Tobago"],["Chad","Tschad"],["Czech Republic","Tschechische Republik"],["Tunisia","Tunesien"],["Turkey","T&#252;rkei"],["Turkmenistan","Turkmenistan"],["Turks and Caicos Islands","Turks- und Caicosinseln"],["Tuvalu","Tuvalu"],["Uganda","Uganda"],["Ukraine","Ukraine"],["Hungary","Ungarn"],["Uruguay","Uruguay"],["Uzbekistan","Usbekistan"],["Vanuatu","Vanuatu"],["Vatican City","Vatikanstadt"],["Venezuela","Venezuela"],["United Arab Emirates","Vereinigte Arabische Emirate"],["United States of America","Vereinigte Staaten von Amerika"],["Vietnam","Vietnam"],["Wallis and Futuna","Wallis und Futuna"],["Belarus","Wei&#223;russland"],["Western Sahara","Westsahara"],["Central African Republic","Zentralafrikanische Republik"],["Cyprus","Zypern"]]
"""
json_data_es = """
[["Spain","Espa&#241;a"],["Gibraltar","Gibraltar"],["Afghanistan","Afganist&#225;n"],["Albania","Albania"],["Germany","Alemania"],["Andorra","Andorra"],["Angola","Angola"],["Anguilla","Anguilla"],["Antarctica","Ant&#225;rtida"],["Antigua and Barbuda","Antigua y Barbuda"],["Netherlands Antilles","Antillas Holandesas"],["Saudi Arabia","Arabia Saudita"],["Algeria","Argelia"],["Argentina","Argentina"],["Armenia","Armenia"],["Aruba","Aruba"],["Australia","Australia"],["Austria","Austria"],["Azerbaijan","Azerbaiy&#225;n"],["Bahamas","Bahamas"],["Bahrain","Bahrein"],["Bangladesh","Bangladesh"],["Barbados","Barbados"],["Belgium","B&#233;lgica"],["Belize","Belice"],["Benin","Benin"],["Bermuda","Bermuda"],["Belarus","Bielorrusia"],["Bolivia","Bolivia"],["Bosnia and Herzegovina","Bosnia Herzegovina"],["Botswana","Botswana"],["Brazil","Brasil"],["Brunei Darussalam","Brunei Darussalam"],["Bulgaria","Bulgaria"],["Burkina Faso","Burkina Faso"],["Myanmar","Burma"],["Burundi","Burundi"],["Bhutan","But&#225;n"],["Cape Verde","Cabo Verde"],["Cambodia","Camboya"],["Cameroon","Camer&#250;n"],["Canada","Canad&#225;"],["Chad","Chad"],["Chile","Chile"],["China","China"],["Cyprus","Chipre"],["Vatican City","Ciudad del Vaticano"],["Colombia","Colombia"],["Comoros","Comoros"],["Congo","Congo"],["Korea, North","Corea del Norte"],["Korea, South","Corea del Sur"],["Ivory Coast","Costa de Marfil"],["Costa Rica","Costa Rica"],["Croatia","Croacia"],["Cuba","Cuba"],["Denmark","Dinamarca"],["Djibouti","Djibouti"],["Dominica","Dominica"],["Ecuador","Ecuador"],["Egypt","Egipto"],["El Salvador","El Salvador"],["United Arab Emirates","Emiratos &#193;rabes Unidos"],["Eritrea","Eritrea"],["Slovakia","Eslovaquia"],["Slovenia","Eslovenia"],["Spain","Espa&#241;a"],["Micronesia, Federated States of","Estados Federados de Micronesia"],["United States of America","Estados Unidos"],["Estonia","Estonia"],["Ethiopia","Etiop&#237;a"],["Fiji","Fiji"],["Philippines","Filipinas"],["Finland","Finlandia"],["France","Francia"],["Gabon","Gab&#243;n"],["Gambia","Gambia"],["Georgia","Georgia"],["Ghana","Ghana"],["Gibraltar","Gibraltar"],["Grenada","Granada"],["Greece","Grecia"],["Greenland","Groenlandia"],["Guadeloupe","Guadalupe"],["Guam","Guam"],["Guatemala","Guatemala"],["French Guiana","Guayana Francesa"],["Guernsey","Guernsey"],["Guinea","Guinea"],["Guinea-Bissau","Guinea-Bissau"],["Equatorial Guinea","Guinea Ecuatorial"],["Guyana","Guyana"],["Haiti","Hait&#237;"],["Netherlands","Holanda"],["Honduras","Honduras"],["Hong Kong","Hong Kong"],["Hungary","Hungr&#237;a"],["India","India"],["Indonesia","Indonesia"],["Iraq","Irak"],["Iran","Ir&#225;n"],["Ireland","Irlanda"],["Bouvet Island","Isla Bouvet"],["Isle of Man","Isla de Man"],["Iceland","Islandia"],["Norfolk Island","Isla Norfolk"],["Cayman Islands","Islas Caim&#225;n"],["Cook Islands","Islas Cook"],["Aland Islands","Islas de Aland"],["Solomon Islands","Islas de Solom&#243;n"],["Faroe Islands","Islas Feroe"],["Heard Island and McDonald Islands","Islas Heard y McDonald"],["Falkland Islands","Islas Malvinas"],["Northern Mariana Islands","Islas Marianas del Norte"],["Marshall Islands","Islas Marshall"],["U.S. Minor Outlying Islands","Islas menores alejadas de los Estados Unidos"],["Turks and Caicos Islands","Islas Turks y Caicos"],["Virgin Islands, U.S.","Islas V&#237;rgenes, EE.UU."],["Virgin Islands, British","Islas V&#237;rgenes. R.U."],["Wallis and Futuna","Islas Wallis y Futuna"],["Israel","Israel"],["Italy","Italia"],["Jamaica","Jamaica"],["Japan","Jap&#243;n"],["Jersey","Jersey"],["Jordan","Jordania"],["Kazakhstan","Kazajist&#225;n"],["Kenya","Kenia"],["Kyrgyzstan","Kirguizist&#225;n"],["Kiribati","Kiribati"],["Kuwait","Kuwait"],["Laos","Laos"],["Lesotho","Lesotho"],["Latvia","Letonia"],["Lebanon","L&#237;bano"],["Liberia","Liberia"],["Libya","Libia"],["Liechtenstein","Liechtenstein"],["Lithuania","Lituania"],["Luxembourg","Luxemburgo"],["Macao","Macao"],["Macedonia","Macedonia"],["Madagascar","Madagascar"],["Malaysia","Malasia"],["Malawi","Malawi"],["Maldives","Maldivas"],["Mali","Mali"],["Malta","Malta"],["Morocco","Marruecos"],["Martinique","Martinica"],["Mauritius","Mauricio"],["Mauritania","Mauritania"],["Mayotte","Mayotte"],["Mexico","M&#233;xico"],["Moldova","Moldavia"],["Monaco","M&#243;naco"],["Mongolia","Mongolia"],["Montenegro","Montenegro"],["Montserrat","Montserrat"],["Mozambique","Mozambique"],["Namibia","Namibia"],["Nauru","Nauru"],["Nepal","Nepal"],["Nicaragua","Nicaragua"],["Niger","Niger"],["Nigeria","Nigeria"],["Niue","Niue"],["Norway","Noruega"],["New Caledonia","Nueva Caledonia"],["New Zealand","Nueva Zelanda"],["Oman","Om&#225;n"],["Pakistan","Pakist&#225;n"],["Palau","Palau"],["Panama","Panam&#225;"],["Papua New Guinea","Papua Nueva Guinea"],["Paraguay","Paraguay"],["Peru","Per&#250;"],["French Polynesia","Polinesia Francesa"],["Poland","Polonia"],["Portugal","Portugal"],["Puerto Rico","Puerto Rico"],["Qatar","Qatar"],["United Kingdom","Reino Unido"],["Central African Republic","Rep&#250;blica Centroafricana"],["Czech Republic","Rep&#250;blica Checa"],["Congo, Democratic Republic of the","Rep&#250;blica Democr&#225;tica del Congo"],["Dominican Republic","Rep&#250;blica Dominicana"],["Reunion","R&#233;union"],["Rwanda","Ruanda"],["Romania","Rumania"],["Russia","Rusia"],["Western Sahara","Sahara Occidental"],["Samoa","Samoa"],["American Samoa","Samoa Americana"],["San Marino","San Marino"],["Saint Helena","Santa Helena"],["Sao Tome and Principe","Santo Tom&#233; y Pr&#237;ncipe"],["Senegal","Senegal"],["Serbia","Serbia"],["Seychelles","Seychelles"],["Sierra Leone","Sierra Leona"],["Singapore","Singapur"],["Syria","Siria"],["Somalia","Somalia"],["Sri Lanka","Sri Lanka"],["St. Kitts and Nevis","St. Kitts y Nevis"],["St. Lucia","St. Luc&#237;a"],["St. Pierre and Miquelon","St. Pierre y Miquelon"],["St. Vincent and the Grenadines","St. Vincent y Granadinas"],["South Africa","Sud&#225;frica"],["Sudan","Sud&#225;n"],["Sweden","Suecia"],["Switzerland","Suiza"],["Suriname","Surin&#225;n"],["Swaziland","Swaziland"],["Tahiti","Tahit&#237;"],["Thailand","Tailandia"],["Taiwan","Taiw&#225;n"],["Tanzania","Tanzania"],["Tajikistan","Tayikist&#225;n"],["British Indian Ocean Territory","Territorio Brit&#225;nico en el Oce&#225;no &#205;ndico"],["French Southern Territories","Territorios Australes Franceses"],["Palestinian Territory, Occupied","Territorios Ocupados de Palestina"],["Togo","Togo"],["Tokelau","Tokelau"],["Tonga","Tonga"],["Trinidad and Tobago","Trinidad y Tobago"],["Tunisia","T&#250;nez"],["Turkmenistan","Turkmenist&#225;n"],["Turkey","Turqu&#237;a"],["Tuvalu","Tuvalu"],["Ukraine","Ucrania"],["Uganda","Uganda"],["Uruguay","Uruguay"],["Uzbekistan","Uzbekist&#225;n"],["Vanuatu","Vanuatu"],["Venezuela","Venezuela"],["Vietnam","Vietnam"],["Yemen","Yemen"],["Zambia","Zambia"],["Zimbabwe","Zimbabwe"]]
"""

country_row_arr = country.split("\n")
for country_row in country_row_arr:
	country_row_info_arr = country_row.split(",")
	if (len(country_row_info_arr) > 3):
		country_info = country_row_info_arr[0].replace("\"", "")
		result_arr = country_info.split("(")

		json_data_en = json_data_en.replace("[\"" + result_arr[1].strip(), "[\"" + result_arr[0].strip())
		json_data_en_gb = json_data_en_gb.replace("[\"" + result_arr[1].strip(), "[\"" + result_arr[0].strip())
		json_data_fr = json_data_fr.replace("[\"" + result_arr[1].strip(), "[\"" + result_arr[0].strip())
		json_data_de = json_data_de.replace("[\"" + result_arr[1].strip(), "[\"" + result_arr[0].strip())
		json_data_es = json_data_es.replace("[\"" + result_arr[1].strip(), "[\"" + result_arr[0].strip())

print("countryList[\"en\"] =" + json_data_en + ";")
print("countryList[\"en-gb\"] =" + json_data_en_gb + ";")
print("countryList[\"fr\"] =" + json_data_fr + ";")
print("countryList[\"de\"] =" + json_data_de + ";")
print("countryList[\"es\"] =" + json_data_es + ";")



